### ISSUE TITLE
TypeError: Cannot read property 'bold' of undefined

### ISSUE THREAD

**Issue by luigimassa** [AdamQuadmon/generator-angular-silex#1]
Hi, 
I tried to istall angular and silex with:
  yo angular-silex

But at the end this is the error

   invoke   angular-silex:common:/usr/local/lib/node_modules/generator-angular-silex/app/index.js
   create     .bowerrc
   create     .editorconfig
   create     .gitattributes
   create     .jshintrc
   create     app/.buildignore
   create     app/.htaccess
   create     app/404.html
   create     app/favicon.ico
   create     app/robots.txt
   create     app/styles/main.css
   create     app/views/main.html
   create     test/runner.html
   create     .gitignore
   invoke   angular-silex:main:/usr/local/lib/node_modules/generator-angular-silex/app/index.js
   create     app/scripts/app.js
   invoke   angular-silex:controller:/usr/local/lib/node_modules/generator-angular-silex/app/index.js
   create     app/scripts/controllers/main.js
   create     test/spec/controllers/main.js

TypeError: Cannot read property 'bold' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-karma/node_modules/yeoman-generator/lib/util/common.js:5:56)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-karma/node_modules/yeoman-generator/lib/base.js:91:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

Can you help me please?

**Comment by luigimassa** [comment]
ops....
 npm cache clean && sudo npm uninstall -g yeoman-generator && sudo npm install -g yeoman-generator

https://github.com/yeoman/generator-webapp/issues/137
